export enum KeyEnum {
  NamePublic = 'namePublic',
  PolicyFile = 'policyFile',
  Date = 'date',
  Description = 'description',
  RegisterTime = 'registerTime',
  FolioNumber = 'folioNumber',
  InsuranceType = 'insuranceType',
  IncapacityType = 'incapacityType',
  OccupationalRiskType = 'occupationalRiskType',
  St2File = 'st2File',
  St7File = 'st7File',
  JustificationCatalog = 'justificationCatalog',
  OmissionCatalog = 'omissionCatalog',
  ActivateTimeOmission = 'activateTimeOmission',
  MaxTimeJustification = 'maxTimeJustification',
  RequestDate = 'requestDate',
  DateStart = 'dateStart',
  DateEnd = 'dateEnd',
  RequestEffectiveDate = 'requestEffectiveDate',
  CalculateDateEnd = 'calculateDateEnd',
  Comments = 'comments',
  Delegate = 'delegate',
  EffectSalaryType = 'effectSalaryType',
  ManageActions = 'manageActions',
  HelpFile = 'helpFile',
  ConfigEvidences = 'configEvidences',
}
