import {
  BarChartOutlined,
  PeopleAltOutlined,
  DescriptionOutlined,
  EventNoteOutlined,
  SettingsOutlined,
  Source,
  AccountTree,
  PermContactCalendar,
  QuestionMark,
  HomeOutlined,
  NotificationsNone,
  ArrowDropUp,
  ArrowDropDown,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  FilterAlt,
  Close,
  Search,
  House,
  ModeEditOutlined,
  PowerSettingsNewOutlined,
  DeleteOutlined,
  MoreHoriz,
  AddCircleOutlined,
  HorizontalRule,
  SaveAlt,
  CheckBox,
  CheckBoxOutlineBlank,
  AddCircleOutline,
  InsertLinkOutlined,
  AccessTimeOutlined,
  FmdGood,
  CalendarTodayOutlined,
  MapOutlined,
  LanOutlined,
  Feed,
  Brush,
  AccessTimeFilled,
  GroupOutlined,
  Check,
  CheckCircleOutline,
  DragHandle,
  ArrowForward,
  PlaylistAdd,
  List,
  ArrowBack,
  SchemaOutlined,
  AccountTreeOutlined,
  AddCircle,
  FormatListBulleted,
  VisibilityOutlined,
  DragIndicator,
  Visibility,
  VisibilityOff,
  ListAlt,
  Save,
  BorderColorOutlined,
  Cached,
  FileDownloadOutlined,
  RadioButtonChecked,
  RadioButtonUnchecked,
  KeyboardDoubleArrowDownOutlined,
  KeyboardDoubleArrowUpOutlined,
  SwitchAccount,
  CheckCircle,
  WatchLaterOutlined,
  Remove,
  CreateNewFolderOutlined,
  AddBoxOutlined,
  IndeterminateCheckBoxOutlined,
  TuneOutlined,
} from '@mui/icons-material'

export const icons = {
  home: <HomeOutlined />,
  barChart: <BarChartOutlined />,
  accountTree: <AccountTree />,
  peopleAlt: <PeopleAltOutlined />,
  description: <DescriptionOutlined />,
  eventNote: <EventNoteOutlined />,
  permContactCalendar: <PermContactCalendar />,
  questionMark: <QuestionMark />,
  source: <Source />,
  settings: <SettingsOutlined />,
  bell: <NotificationsNone />,
  arrowUp: <ArrowDropUp />,
  arrowDown: <ArrowDropDown />,
  arrowLeft: <KeyboardArrowLeft />,
  arrowRight: <KeyboardArrowRight />,
  filterAlt: <FilterAlt />,
  close: <Close />,
  search: <Search />,
  house: <House />,
  edit: <ModeEditOutlined />,
  power: <PowerSettingsNewOutlined />,
  delete: <DeleteOutlined />,
  more: <MoreHoriz />,
  add: <AddCircleOutlined />,
  link: <InsertLinkOutlined />,
  hr: <HorizontalRule />,
  save: <SaveAlt />,
  checkBoxOutlineBlank: <CheckBoxOutlineBlank fontSize="small" />,
  checkBoxIcon: <CheckBox fontSize="small" />,
  addCircleOutline: <AddCircleOutline />,
  accessTime: <AccessTimeOutlined />,
  fmdGood: <FmdGood />,
  calendarToday: <CalendarTodayOutlined />,
  map: <MapOutlined />,
  lan: <LanOutlined />,
  feed: <Feed />,
  brush: <Brush />,
  accessTimeFilled: <AccessTimeFilled />,
  group: <GroupOutlined />,
  check: <Check />,
  checkCircleOutline: <CheckCircleOutline />,
  dragHandle: <DragHandle />,
  arrowForward: <ArrowForward />,
  catalogs: <PlaylistAdd />,
  list: <List />,
  arrowBack: <ArrowBack />,
  schema: <SchemaOutlined />,
  accountTreeOutlined: <AccountTreeOutlined />,
  addCircle: <AddCircle />,
  formatList: <FormatListBulleted />,
  Visibility: <VisibilityOutlined />,
  dragIndicator: <DragIndicator />,
  visibility: <Visibility />,
  VisibilityOff: <VisibilityOff />,
  listAlt: <ListAlt />,
  saveDis: <Save />,
  borderColorEdit: <BorderColorOutlined />,
  cached: <Cached />,
  Download: <FileDownloadOutlined />,
  radioButtonChecked: <RadioButtonChecked />,
  radioButtonUnchecked: <RadioButtonUnchecked />,
  doubleArrowDown: <KeyboardDoubleArrowDownOutlined />,
  doubleArrowUp: <KeyboardDoubleArrowUpOutlined />,
  switchAccount: <SwitchAccount />,
  CheckCircle: <CheckCircle />,
  WatchLaterOutlined: <WatchLaterOutlined />,
  Remove: <Remove />,
  CreateNewFolderOutlined: <CreateNewFolderOutlined />,
  AddBoxOutlined: <AddBoxOutlined />,
  IndeterminateCheckBoxOutlined: <IndeterminateCheckBoxOutlined />,
  TuneOutlined: <TuneOutlined />,
}
