export enum PathName {
  Home = '/inicio',
  Setup = '/configuracion',
  TermsConditions = '/terminos-condiciones',
  UserSearch = '/buscar-usuario',
  UsersModule = '/usuarios/*',
  UsersView = '/usuarios/buscar-usuario',
  IncidentsModule = 'incidencias/*',
  IncidentsView = '/incidencias',
  detail = '/detalle/:id',
  detailView = '/incidencias/detalle',
  WorkingDays = '/jornadas-de-trabajo',
  NewSchedule = '/nuevo-horario',
  NewScheduleView = '/jornadas-de-trabajo/nuevo-horario',
  EditSchedule = '/editar-horario',
  EditScheduleView = '/jornadas-de-trabajo/editar-horario',
  CatalogMotifsModule = 'catalogos-de-motivos/*',
  CatalogMotifsView = '/catalogos-de-motivos/',
  CatalogOtherModule = 'listas-desplegables/*',
  CatalogOtherView = '/listas-desplegables/',
  LocationModule = 'localizacion/*',
  LocationView = '/localizacion',

  //------ eventos y calendarios
  EventsAndCalendarModule = '/calendario-y-eventos/*',
  EventsAndCalendar = '/calendario-y-eventos',
  Events = '/calendario-y-eventos/eventos',
  eventDescription = '/calendario-y-eventos/eventos/descripcion',
  eventDateAndOccurrence = '/calendario-y-eventos/eventos/fecha-y-ocurrencia',
  eventGuests = '/calendario-y-eventos/eventos/invitados',

  UpdateLocation = '/actualizar-localizacion',
  UpdateLocationView = '/localizacion/actualizar-localizacion',
  Authentication = '/*',
  Login = '/',
  configuration = '/configuration',
  operationStructure = '/esquema-geografico',
  //modelos dinamicos
  costCenter = 'centro-de-costos',
  cashBenefits = 'tabulador',
  positions = 'puestos',
  jobTitles = 'cargos',
  stores = 'sucursales',
  taxesCategories = 'categorias-de-puestos',
  //

  organizacionalStructure = '/estructura-organizacional',
  operatingStructureView = '/data-structure/operating-structure',
  hierarchySummary = '/jerarquia-de-niveles',
  UserStructure = '/estructura-de-la-compania/',
  DataStructure = '/estructura-de-la-compania/empresa',
  dataStructureRelationshipConfiguration = '/estructura-de-la-compania/empresa/relaciones-estructuras',
  employeeStructure = '/estructura-de-la-compania/empleado',
  employeeStructureWeighting = '/estructura-de-la-compania/empleado/ponderar-secciones',
  weighting = '/ponderar-secciones',
  DataCreation = 'creacion-de-datos',
  //modelos dinamicos creacion de estructura
  costCenterView = '/estructura-de-la-compania/empresa/centro-de-costos',
  positionsView = '/estructura-de-la-compania/empresa/puestos',
  storesView = '/estructura-de-la-compania/empresa/sucursales',
  taxesCategoriesView = '/estructura-de-la-compania/empresa/categorias-de-puestos',
  cashBenefitsView = '/estructura-de-la-compania/empresa/tabulador',
  jobTitlesView = '/estructura-de-la-compania/empresa/cargos',
  //
  hierarchySummaryView = '/estructura-de-la-compania/empresa/esquema-geografico/jerarquia-de-niveles',
  hierarchySummaryOrganizationStructure = '/estructura-de-la-compania/empresa/estructura-organizacional/jerarquia-de-niveles',
  listDataCreation = '/estructura-de-la-compania/empresa/esquema-geografico/creacion-de-datos',
  listOrganizationalStructure = '/estructura-de-la-compania/empresa/estructura-organizacional/creacion-de-datos',
  creationDataEntity = '/estructura-de-la-compania/empresa/esquema-geografico/creacion-de-datos/crear-entidad',
  creationDataEntityOrganization = '/estructura-de-la-compania/empresa/estructura-organizacional/creacion-de-datos/crear-entidad',
  createEntity = '/crear-entidad',
  OperatingLevels = '/niveles-operativos',
  NewLevel = '/nuevo-nivel',
  newLevelView = '/niveles-operativos/nuevo-nivel',
  RecoverAccount = 'recuperar-cuenta',
  RestorePassword = '/recuperar-cuenta/restaurar-contrasena',
  tableOperatingSchema = '/estructura-de-la-compania/empresa/esquema-geografico/gestion-de-niveles/lista-de-niveles-operativos',
  levelHierarchy = '/estructura-de-la-compania/empresa/esquema-geografico/gerarquia-de-niveles/estructura',
  recordCreation = '/estructura-de-la-compania/empresa/esquema-geografico/creacion-de-registros/formulario',
  operatingEdit = '/estructura-de-la-compania/empresa/esquema-geografico/creacion-de-datos/editar-nivel-operativo',
  organizationalLevelFormEdit = '/estructura-de-la-compania/empresa/estructura-organizacional/creacion-de-datos/editar-nivel-operativo',
  operatingLevelList = '/lista-de-niveles-operativos',
  operatingLevelForm = '/crear-nivel-operativo',
  operatingLevelFormEdit = '/editar-nivel-operativo',

  //GESTIONAR operativo
  organizationManagement = '/gestionar-organizacion',

  structure = '/estructura',
  strListInstances = '/estructura/lista-de-instancias',
  listInstances = '/lista-de-instancias',
  editInsOrnManagement = '/editar-instancia',
  creationInsOrnManagement = '/crear-instancia',
  treeOrgManagement = '/arbol-de-jerarquia',
  creationInsGeoManagementView = '/gestionar-organizacion/estructura-geografica/crear-instancia',
  creationInsOrnManagementView = '/gestionar-organizacion/estructura-organizativa/crear-instancia',

  //GESTIONAR organizacional

  //Instanciacion modelos dinamicos
  //tablas
  instanceCostCenterView = '/gestionar-organizacion/centro-de-costos',
  instancePositionsView = '/gestionar-organizacion/puestos',
  instanceStoresView = '/gestionar-organizacion/sucursales',
  instanceTaxesCategoriesView = '/gestionar-organizacion/categorias-de-puestos',
  instanceCashBenefitsView = '/gestionar-organizacion/tabulador',
  instanceJobTitlesView = '/gestionar-organizacion/cargos',
  //creacion
  instanceCostCenterCreation = '/gestionar-organizacion/centro-de-costos/crear-instancia',
  instancePositionsCreation = '/gestionar-organizacion/puestos/crear-instancia',
  instanceStoresCreation = '/gestionar-organizacion/sucursales/crear-instancia',
  instanceTaxesCategoriesCreation = '/gestionar-organizacion/categorias-de-puestos/crear-instancia',
  instanceCashBenefitsCreation = '/gestionar-organizacion/tabulador/crear-instancia',
  instanceJobTitlesCreation = '/gestionar-organizacion/cargos/crear-instancia',
  //edicion
  instanceCostCenterEdit = '/gestionar-organizacion/centro-de-costos/editar-instancia',
  instancePositionsEdit = '/gestionar-organizacion/puestos/editar-instancia',
  instanceStoresEdit = '/gestionar-organizacion/sucursales/editar-instancia',
  instanceTaxesCategoriesEdit = '/gestionar-organizacion/categorias-de-puestos/editar-instancia',
  instanceCashBenefitsEdit = '/gestionar-organizacion/tabulador/editar-instancia',
  instanceJobTitlesEdit = '/gestionar-organizacion/cargos/editar-instancia',
  //visualizacion
  instanceCostCenterDetail = '/gestionar-organizacion/centro-de-costos/detalle',
  instancePositionsDetail = '/gestionar-organizacion/puestos/detalle',
  instanceStoresDetail = '/gestionar-organizacion/sucursales/detalle',
  instanceTaxesCategoriesDetail = '/gestionar-organizacion/categorias-de-puestos/detalle',
  instanceCashBenefitsDetail = '/gestionar-organizacion/tabulador/detalle',
  instanceJobTitlesDetail = '/gestionar-organizacion/cargos/detalle',
  //
  editInsGeoManagementView = '/gestionar-organizacion/estructura-geografica/editar-instancia',
  editInsOrnManagementView = '/gestionar-organizacion/estructura-organizativa/editar-instancia',
  listGeographicalStructure = '/gestionar-organizacion/estructura-geografica/lista-de-instancias',
  listOrganizationalStr = '/gestionar-organizacion/estructura-organizativa/lista-de-instancias',
  treeGeoManagementview = '/gestionar-organizacion/estructura-geografica/arbol-de-jerarquia',
  treeOrgManagementview = '/gestionar-organizacion/estructura-organizativa/arbol-de-jerarquia',
  geographicalStructure = '/estructura-geografica',
  organizationalStructure = '/estructura-organizativa',

  //modelos dinamicos creacion de perfil
  personalInformation = '/estructura-de-la-compania/empleado/informacion-personal',
  biographicalInformation = '/estructura-de-la-compania/empleado/informacion-biografica',
  personalData = '/estructura-de-la-compania/empleado/datos-personales',
  identifyDocument = '/estructura-de-la-compania/empleado/documento-de-identidad',
  address = '/estructura-de-la-compania/empleado/direccion',
  contactInformation = '/estructura-de-la-compania/empleado/informacion-contacto',
  educationInformation = '/estructura-de-la-compania/empleado/informacion-educativa',
  emergencyContact = '/estructura-de-la-compania/empleado/contacto-de-emergencia',
  dependents = '/estructura-de-la-compania/empleado/dependientes',
  jobInformation = '/estructura-de-la-compania/empleado/informacion-puesto',
  payrollInformation = '/estructura-de-la-compania/empleado/informacion-nomina',
  compensation = '/estructura-de-la-compania/empleado/compensaciones',
  workHistory = '/estructura-de-la-compania/empleado/registro-laboral',
  paymentInformation = '/estructura-de-la-compania/empleado/informacion-pago',
  humanCapital = '/estructura-de-la-compania/empleado/capital-humano',
  workSchedule = '/estructura-de-la-compania/empleado/jornada',
  documents = '/estructura-de-la-compania/empleado/documentos',

  //colaboradores
  contributorsModule = '/colaboradores',
  contributorsListDetail = '/colaboradores/detalle',
  contributorsCreate = '/colaboradores/crear',
  contributorsEdit = '/colaboradores/editar',
}

export const keyFromPath = (path: string) => {
  const key = Object.keys(PathName).find((key) => PathName[key as keyof typeof PathName] === path)
  return `/${key}` ?? ''
}
