export const NamesEnum: { [key: string]: string } = {
  PSPI01: 'Información Personal',
  PSBI02: 'Información Biográfica',
  PSPD03: 'Datos Personales',
  PSID04: 'Documentos de Identificación Personal',
  PSAS05: 'Dirección',
  PSCI06: 'Información Contacto',
  PSEI07: 'Información Educativa',
  PSEC08: 'Contacto de Emergencia',
  PSDP09: 'Dependientes',
  PSJI10: 'Información Puesto',
  PSPN11: 'Información Nómina',
  PSCT12: 'Compensaciones',
  PSWH13: 'Registro Laboral',
  PSPM14: 'Información Pago',
  PSHC15: 'Capital Humano',
  //PSWS16: 'Jornada',
  PSDC17: 'Documentos',
}
