export const dataLocation = [
  { id: 1, name: '01 enero - Año Nuevo', isActive: false },
  { id: 2, name: '05 febrero - Día de la Constitución', isActive: false },
  { id: 3, name: '21 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 4, name: '02 enero - Año Nuevo', isActive: false },
  { id: 5, name: '06 febrero - Día de la Constitución', isActive: false },
  { id: 6, name: '22 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 7, name: '03 enero - Año Nuevo', isActive: false },
  { id: 8, name: '07 febrero - Día de la Constitución', isActive: false },
  { id: 9, name: '23 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 10, name: '04 enero - Año Nuevo', isActive: false },
  { id: 11, name: '08 febrero - Día de la Constitución', isActive: false },
  { id: 12, name: '24 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 13, name: '05 enero - Año Nuevo', isActive: false },
  { id: 14, name: '09 febrero - Día de la Constitución', isActive: false },
  { id: 15, name: '25 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 16, name: '06 enero - Año Nuevo', isActive: false },
  { id: 17, name: '10 febrero - Día de la Constitución', isActive: false },
  { id: 18, name: '26 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 19, name: '11 febrero - Día de la Constitución', isActive: false },
  { id: 20, name: '27 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 1, name: '01 enero - Año Nuevo', isActive: false },
  { id: 2, name: '05 febrero - Día de la Constitución', isActive: false },
  { id: 3, name: '21 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 4, name: '02 enero - Año Nuevo', isActive: false },
  { id: 5, name: '06 febrero - Día de la Constitución', isActive: false },
  { id: 6, name: '22 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 7, name: '03 enero - Año Nuevo', isActive: false },
  { id: 8, name: '07 febrero - Día de la Constitución', isActive: false },
  { id: 9, name: '23 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 10, name: '04 enero - Año Nuevo', isActive: false },
  { id: 11, name: '08 febrero - Día de la Constitución', isActive: false },
  { id: 12, name: '24 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 13, name: '05 enero - Año Nuevo', isActive: false },
  { id: 14, name: '09 febrero - Día de la Constitución', isActive: false },
  { id: 15, name: '25 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 16, name: '06 enero - Año Nuevo', isActive: false },
  { id: 17, name: '10 febrero - Día de la Constitución', isActive: false },
  { id: 18, name: '26 marzo - Natalicio de Benito Juárez', isActive: false },
  { id: 19, name: '11 febrero - Día de la Constitución', isActive: false },
  { id: 20, name: '27 marzo - Natalicio de Benito Juárez', isActive: false },
]
